SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA vk;
USE vk;

CREATE TABLE question (
    question_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(1000) NOT NULL,
    answer_A VARCHAR(50) NOT NULL,
    answer_B VARCHAR(50) NOT NULL,
    answer_C VARCHAR(50) NOT NULL,
    answer_D VARCHAR(50),
    answer_E VARCHAR(50),
    right_answer CHAR NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user (
    user_id INTEGER NOT NULL PRIMARY KEY,
    question_id INTEGER NOT NULL,
    answer CHAR NOT NULL,
    cor_answer CHAR NOT NULL,
    matches CHAR NOT NULL,
    answer_number INTEGER(2) NOT NULL,
    right_answer_number INTEGER(2) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
